version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "valorotask-stack"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-15wvbx85uk2j5"
s3_prefix = "valorotask-stack"
region = "us-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "DBSecretName=\"valorodb\" ValoroTaskDBSchemaStackName=\"dbschema-stack\" DBEntryPoint=\"valoro.cxgqiidtivfp.us-west-2.rds.amazonaws.com\""
